name: Tessera Consultancy
favicon: null
layout_spectrum: 0.21769
typography_spectrum: 0.19705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#acd7db'
    - '#45484a'
    - '#a58a7d'
    - '#93a8bd'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.04985084640793502
purpose: []
